[build]
# Optimize dependencies for size
[profile.dev]
opt-level = "z"  # Optimize for size
lto = "thin"     # Link Time Optimization
codegen-units = 1
panic = "abort"  # Smaller binary by using abort instead of unwinding

[profile.release]
opt-level = "z"  # Optimize for size
lto = "fat"      # Use fat LTO for maximum optimization
codegen-units = 1
panic = "abort"  # Smaller binary by using abort instead of unwinding
strip = true    # Remove debug symbols from release builds

# Optimize dependencies
[profile.dev.package."*"]
opt-level = 3

[profile.release.package."*"]
opt-level = 3

# Optimize build process
[net]
git-fetch-with-cli = true  # Use the git CLI for git operations

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-C", "link-arg=/NODEFAULTLIB:LIBCMT"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
